- hosts: all
  connection: local
  become: yes
  become_user: root
  tasks:
  - name: add dns line
    lineinfile:
      dest: /etc/resolv.conf
      line: "nameserver    192.168.1.220"
  - name: join AD
    include_tasks: ./playbooks/join_ad.yml

