# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables Section
$distro = ""

# Scripting Section
$clone_distro = <<-EOH
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y apache2 mysql-server php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php
sudo systemctl restart apache2
cd /var/www/html/
git clone https://github.com/douglas-evert/server_manager.git
ip addr
EOH

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
  config.vm.provider "virtualbox" do |vmbox|
    vmbox.name = "ubuntu_lamp"
  end
  config.vm.provision "shell", inline: $clone_distro
end
